# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "cf-pf"
client_id = "f667211284fc0a2a919282a569390366"
application_url = "https://identity-detect-robin-ghana.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, read_themes, write_themes"

[auth]
redirect_urls = [
  "https://identity-detect-robin-ghana.trycloudflare.com/auth/callback",
  "https://identity-detect-robin-ghana.trycloudflare.com/auth/shopify/callback",
  "https://identity-detect-robin-ghana.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "causalfunnel-app-testing.myshopify.com"
